version: '3.9'

services:

  decision-tree:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8000:3000'
    volumes:
      - type: bind
        source: .
        target: /home/node
      - type: bind
        source: ./Common/
        target: /home/node/src/Common/
    tty: true
    links:
      - "dev-db-tree:link-db-tree"
    networks:
      - urgencetree-decision-tree

  dev-db-tree:
    ports:
      - '8001:27017'
    image: mongo:latest
    volumes:
      - ./db/db:/data/db
      - ./db/config/dev-mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - ./development.env
      - ./db/config/development.env
    networks:
      - urgencetree-decision-tree
    restart: always

  image-decision-tree:
    image: urgencetree/server-decision-tree:latest
    ports:
      - '8000:3000'
    tty: true


  image-client:
    image: urgencetree/web-client:latest
    ports:
      - '80:80'
    tty: true

networks:
  urgencetree-decision-tree: