name: ci

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: urgencetree/server-decision-tree:latest
          file: "./Dockerfile.prod"

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Get dependencies
      run: go mod download -x

    - name: Build
      working-directory: ./src
      run: go build -v ./...

    - name: Test
      working-directory: ./src
      run: go test -v ./...

