name: Docker Build

on:
  push:
    branches:
      - USDT-34-Github-action-dockerfile

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t sdt_questions_img .

    # You can add additional steps here, such as running tests on the image.

    - name: Save Docker Image as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: |
          /var/lib/docker
          /var/run/docker.sock