name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Save bot credentials
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.BOT_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 0700 ~/.ssh/id_rsa
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: urgencetree/server-decision-tree:latest
          file: "./Dockerfile.prod"
